services:
  app:
    container_name: yfinance_app
    build: .
    env_file:
      - ./.env
    networks:
      - shared-net
    volumes:
      - .:/app
    depends_on:
      - db
    restart: always
  db:
    container_name: yfinance_db
    image: postgres:12
    env_file:
      - ./.env
    ports:
      - "5433:5432"
    networks:
      - shared-net
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always

volumes:
  postgres_data:

networks:
  shared-net: