services:
  app:
    build: .
    volumes:
      - .:/app
      - ../parameter.json:/app/parameter.json
    depends_on:
      - db
    env_file:
      - ./.env
    networks:
      - shared-net
  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    networks:
      - shared-net
    ports:
      - "5433:5432"

volumes:
  postgres_data:

networks:
  shared-net: