services:
  app:
    build: ./app
    volumes:
      - ./app:/usr/src/app
      - ../parameter.json:/usr/src/app/parameter.json
    depends_on:
      - db
    env_file:
      - ../.env
    networks:
      - shared-net
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../.env
    networks:
      - shared-net
    ports:
      - "5433:5432"

volumes:
  postgres_data:

networks:
  shared-net: